# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual trainingsem_seg_pred

BASE_TASK_CONFIG_PATH: "configs/tasks/objectnav_mp3d_il.yaml"
TRAINER_NAME: "ddp-il-trainer"
ENV_NAME: NavRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/objectnav/objectnav_il/overfitting/sem_seg_pred/seed_1/ckpt_20"
VIDEO_DIR: "video_dir/objectnav/objectnav_il/overfitting/sem_seg_pred/seed_1/ckpt_20"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/objectnav/objectnav_il/overfitting/sem_seg_pred/seed_1/ckpt.20.pth"
SHOW_TOP_DOWN_MAP: False
NUM_PROCESSES: 8
CHECKPOINT_FOLDER: "data/new_checkpoints/objectnav/objectnav_il/overfitting/sem_seg_pred/seed_1/"
OUTPUT_LOG_DIR: data/objectnav/logs
LOG_INTERVAL: 10
LOG_METRICS: True
CHECKPOINT_INTERVAL: 500
SENSORS: ['RGB_SENSOR', 'SEMANTIC_SENSOR', 'DEPTH_SENSOR']
RESULTS_DIR: "data/objectnav/results/objectnav_il/overfitting/sem_seg_pred/{split}/{type}"
EVAL_RESUTLS_DIR: "data/objectnav/results/"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "val"
  meta_file: "tb/objectnav/objectnav_il/overfitting/sem_seg_pred/seed_1/ckpt_20/evaluation_meta.json"
NUM_UPDATES: 16000
WANDB:
  GROUP_NAME: "SemSeg"
  PROJECT_NAME: "objectnav_il"
  JOB_TYPE: "train"
  MODE: "online"
  RESUME: "must"
  TAGS: ["cross_entropy"]
  LOG_DIR: "wandb/"

IL:
  POLICY:
    name: "ObjectNavILPolicy"
  USE_IW: True
  distrib_backend: NCCL
  BehaviorCloning:
    lr: 0.001
    encoder_lr: 0.001
    eps: 1.0e-5
    clip_param: 0.2
    num_mini_batch: 2
    max_grad_norm: 0.2
    num_steps: 64
    use_linear_clip_decay: False
    use_linear_lr_decay: True
    reward_window_size: 50
    sync_frac: 0.6

    pretrained: False
    pretrained_weights: "None"
  
  Finetune:
    freeze_visual_encoders: False

RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -1e-3

MODEL:
  hm3d_goal: False
  embed_sge: True
  USE_SEMANTICS: True
  USE_PRED_SEMANTICS: True
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
  deterministic_eval: True
  SEMANTIC_PREDICTOR:
    name: "rednet"
    REDNET:
      pretrained_weights: "data/rednet-models/rednet_semmap_mp3d_40_v2_vince.pth"
      # pretrained_weights: "data/rednet-models/rednet_semmap_hm3d_6.pth"
      num_classes: 29
    DETIC:
      pretrained_weights: "Detic/models/Detic_LbaseI_CLIP_R5021k_640b64_4x_ft4x_max-size.pth"
      config: "Detic/configs/Detic_LbaseI_CLIP_R5021k_640b64_4x_ft4x_max-size.yaml"
      score_threshold: 0.3
    SHAPECONV:
      config: "configs/semantic_predictor/shapeconv/hm3d_deeplabv3plus_resnet101_baseline.py"
      pretrained_weights: "data/new_checkpoints/mmdet/semantic_predictor/shapeconv/shapeconv_23cat_best_class_acc_with_bg.pth"
      only_rednet_cats: False
  SEMANTIC_ENCODER:
    cnn_type: "ResnetSemSegEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
    embedding_size: 4
    is_hm3d: False
    is_thda: True
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
    normalize_visual_inputs: False
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 2048
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  CRITIC:
    no_critic: True
    mlp_critic: False
    hidden_dim: 512
